export const Players = [
  {
    name: "afonso-fazendeiro",
    image: "/assets/pro1.png",
    dob: "18/07/1998",
    position: "Left-side (Right-Handed Player)",
    mainTitles: [
      "European Games 2023, Krakow, Poland, 3rd Place",
      "World Padel Championship 2022, 3rd Place",
      "FPP Master 2022, 1st Place",
    ],
    fppRanking: 12,
    wptRanking: 100,
    fipRanking: null,
    academyTime: "2022/2023",
    colStart: 1,
  },
  {
    name: "constanca-gorito",
    image: "/assets/pro2.png",
    dob: "17/09/2007",
    position: "Right-side (Right-Handed Player)",
    mainTitles: [
      "Open Juniors World Padel Championship 2023, 3rd Place",
      "Sub-16 Nacional Championship 2023, 1st Place",
      "Nacional Championship 2023, Semifinalist",
    ],
    fppRanking: 9,
    wptRanking: null,
    fipRanking: 324,
    academyTime: "2022/2024",
    colStart: 2,
  },
  {
    name: "bernardo-roque",
    image: "/assets/pro3.png",
    dob: "17/03/1998",
    position: "Right-side (Left-Handed Player)",
    mainTitles: ["FIP Promotion Cittá Del Templi 2023, 3rd Place"],
    fppRanking: 56,
    wptRanking: null,
    fipRanking: 558,
    academyTime: "2021/2023",
    colStart: 1,
  },
  {
    name: "plinio-ferrao",
    image: "/assets/pro4.png",
    dob: "01/03/2002",
    position: "Left-side (Right-Handed Player)",
    mainTitles: [],
    fppRanking: 51,
    wptRanking: null,
    fipRanking: 1601,
    academyTime: "2021/2023",
    colStart: 2,
  },
  {
    name: "bernardo-monteiro",
    image: "/assets/pro5.png",
    dob: "",
    position: "Right-side (Right-Handed Player)",
    mainTitles: [],
    fppRanking: 57,
    wptRanking: null,
    fipRanking: null,
    academyTime: "2021/2023",
    colStart: 1,
  },
  {
    name: "martim-silva",
    image: "/assets/pro6.png",
    dob: "",
    position: "Right-side (Right-Handed Player)",
    mainTitles: [],
    fppRanking: 44,
    wptRanking: null,
    fipRanking: null,
    academyTime: "2022/2023",
    colStart: 2,
  },
  {
    name: "sofia-formigal",
    image: "/assets/pro7.png",
    dob: "",
    position: "Right-side (Right-Handed Player)",
    mainTitles: [],
    fppRanking: "",
    wptRanking: null,
    fipRanking: null,
    academyTime: "2022/2023",
    colStart: 2,
  },
]

export const Clinics = [
  {
    name: "ibe",
    image: "/assets/LOGO_IBE.png",
    width: 267,
    height: 112,
    color: "Blue",
    colStart: 1,
  },
  {
    name: "train-as-a-pro",
    image: "/assets/LOGO_TRAIN_AS_A_PRO.png",
    width: 231,
    height: 84,
    color: "Green",
    colStart: 2,
  },
  {
    name: "master-clinic-evolution",
    image: "/assets/LOGO_MASTER_CLINIC_EVOLUTION.png",
    width: 285,
    height: 116,
    color: "Green",
    colStart: 1,
  },
  {
    name: "padel-wonderland",
    image: "/assets/LOGO_PADEL_WONDERLAND.png",
    width: 418,
    height: 70,
    color: "Blue",
    colStart: 2,
  },
  {
    name: "master-clinic",
    image: "/assets/LOGO_MASTER_CLINIC.png",
    width: 310,
    height: 93,
    color: "Blue",
    colStart: 1,
  },
  {
    name: "padel-company-big-day",
    image: "/assets/LOGO_PADEL_COMPANY_BIG_DAY.png",
    width: 353,
    height: 133,
    color: "Green",
    colStart: 2,
  },
  {
    name: "",
    image: null,
    color: "Green",
    colStart: 1,
  },
  {
    name: "play-like-a-pro",
    image: "/assets/LOGO_PLAY_LIKE_A_PRO.png",
    width: 231,
    height: 92,
    color: "Blue",
    colStart: 2,
  },
]
